[project]
name = "YA_Common"
version = "0.1.0"
description = "YA Common Utils"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "art>=6.5",
    "httpx>=0.28.1",
    "loguru>=0.7.3",
    "mcp[cli]>=1.14.0",
    "pyyaml>=6.0.2",
]
